[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip', 'chromium', 'chromedriver']

[phases.install]
cmds = ['python -m ensurepip --upgrade', 'python -m pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.build]
cmds = ['mkdir -p screenshots']

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT'
