[phases.setup]
nixPkgs = ['python310', 'python310Packages.pip', 'python310Packages.setuptools', 'chromium', 'chromedriver']

[phases.install]
cmds = [
    'python --version',
    'python -m ensurepip --upgrade',
    'python -m pip install --upgrade pip',
    'pip install -r requirements.txt --no-cache-dir'
]

[phases.build]
cmds = ['mkdir -p screenshots']

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT'
