[phases.setup]
nixPkgs = ['python3', 'chromium', 'chromedriver']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['mkdir -p screenshots']

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT'
